[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tricahue"
version = "0.0.b5"
description = "This package extracts experimental data and metadata, converts to standard formats, uploads to SynBioHub and Flapjack, and connects them"
readme = "README.md"
dependencies = [
    "excel2flapjack==1.1.1",
    "excel2sbol @ git+https://github.com/DRAGGON-Lab/Excel-to-SBOL.git@gui",
    "requests==2.25.1",
    "packaging==21.3"
]
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE.*"]
keywords = ["SBOL", "test", "data", "experimental", "synthetic biology"]
authors = [
  { name="Gonzalo Vidal", email="gonzalo.vidalpena@colorado.edu" }
]
maintainers = [
  { name="Gonzalo Vidal", email="gonzalo.vidalpena@colorado.edu" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]



[project.optional-dependencies]
test = [
  "pytest < 5.0.0",
  "pytest-cov[all]"
]

[project.urls]
"Homepage" = "https://github.com/MyersResearchGroup/Tricahue"
"Bug Tracker" = "https://github.com/MyersResearchGroup/Tricahue/issues"
